const test = require("../auth/test.js");
const loginRoutes = require("../auth/login.js");
const updateLoginCredentialsRoures = require("../auth/updateLoginCredentialsRoures.js");
const logoutRoutes = require("../auth/logout.js");
const checkUsername = require("../auth/checkUsername.js");
const resetPassword = require("../auth/resetPassword.js");
const registerUserRoutes = require("./generics/registerUserRoutes.js");
const getGendersRoutes = require("./generics/getGendersRoutes.js");
const updateProfileRoutes = require("./generics/updateProfileRoutes.js");
const getUsersRoutes = require("./generics/getUsersRoutes.js");
const toggleAdminRoleRoutes = require("./admins/toggleAdminRoleRoutes.js");
const toggleBlockUserRoutes = require("./admins/toggleBlockUserRoutes.js");
const savePaymentDetailsRoutes = require("./admins/configurations/savePaymentDetailsRoutes.js");
const getPaymentDetailsRoutes = require("./admins/configurations/getPaymentDetailsRoutes.js");
const deletePaymentDetailsRoutes = require("./admins/configurations/deletePaymentDetailsRoutes.js");
const saveLoanTypeRoutes = require("./admins/configurations/saveLoanTypeRoutes.js");
const getLoanTypesRoutes = require("./admins/configurations/getLoanTypesRoutes.js");
const deleteLoanTypeRoutes = require("./admins/configurations/deleteLoanTypeRoutes.js");
const saveInterestRatesRoutes = require("./admins/configurations/saveInterestRatesRoutes.js");
const getInterestRatesRoutes = require("./admins/configurations/getInterestRatesRoutes.js");
const deleteInterestRatesRoutes = require("./admins/configurations/deleteInterestRatesRoutes.js");
const saveTermsAndConditionsRoutes = require("./admins/configurations/saveTermsAndConditionsRoutes.js");
const getTermsAndConditionsRoutes = require("./admins/configurations/getTermsAndConditionsRoutes.js");
const deleteTermsAndConditionsRoutes = require("./admins/configurations/deleteTermsAndConditionsRoutes.js");
const getNumWeeksRoutes = require("./admins/loanManagement/newLoans/getNumWeeksRoutes.js");
const saveNewLoanRoutes = require("./admins/loanManagement/newLoans/saveNewLoanRoutes.js");
const getUnclearedLoansRoutes = require("./admins/loanManagement/newLoans/getUnclearedLoansRoutes.js");
const getOverdueLoansRoutes = require("./admins/loanManagement/newLoans/getOverdueLoansRoutes.js");
const deleteLoanRoutes = require("./admins/loanManagement/newLoans/deleteLoanRoutes.js");
const loanRepaymentsRoutes = require("./admins/loanManagement/loanRepayments/loanRepaymentsRoutes.js");
const renewLoanRoutes = require("./admins/loanManagement/loanRepayments/renewLoanRoutes.js");
const getLoanBalanceRoutes = require("./admins/loanManagement/loanRepayments/getLoanBalanceRoutes.js");
const getClearedLoansRoutes = require("./admins/loanManagement/clearedLoans/getClearedLoansRoutes.js");
const saveLoanApplicationRoutes = require("./customers/loans/loanApplications/saveLoanApplicationRoutes.js");
const deleteLoanApplicationRoutes = require("./customers/loans/loanApplications/deleteLoanApplicationRoutes.js");
const getLoanApplicationsRoutes = require("./customers/loans/loanApplications/getLoanApplicationsRoutes.js");
const getLoanApplicationsAsAdminRoutes = require("./admins/loanManagement/loanApplications/getLoanApplicationsAsAdminRoutes.js");
const declineLoanApplicationRoutes = require("./admins/loanManagement/loanApplications/declineLoanApplicationRoutes.js");
const approveLoanRoutes = require("./admins/loanManagement/loanApplications/approveLoanRoutes.js");
const getCustomerLoansRoutes = require("./customers/loans/customerLoans/getCustomerLoansRoutes.js");
const getMessagesRoutes = require("./admins/configurations/messeges/getMessagesRoutes.js");
const updateMessageRoutes = require("./admins/configurations/messeges/updateMessageRoutes.js");
const setSystemAttributesRoutes = require("./admins/configurations/system/setSystemAttributesRoutes.js");
const getSystemAttributesRoutes = require("./admins/configurations/system/getSystemAttributesRoutes.js");
const getUserDetailsRoutes = require("./generics/getUserDetailsRoutes.js");
const updateDPRoutes = require("./generics/updateDPRoutes.js");
const sendSMSRoutes = require("./admins/configurations/messeges/sendSMSROutes.js");
const getCustomerLoansStatsRoutes = require("./customers/dashboard/getCustomerLoansStatsRoutes.js");
const getAdminLoanStatsRoutes = require("./admins/dashboard/getAdminLoanStatsRoutes.js");
const getUserTypeRoutes = require("./generics/getUserTypeRoutes.js");
const getUserNotificationsRoutes = require("./generics/getUserNotificationsRoutes.js");
const markViewedNotificationsRoutes = require("./generics/markViewedNotificationsRoutes.js");
const getNumNewNotificationsRoutes = require("./generics/getNumNewNotificationsRoutes.js");
const deleteNotificationRoutes = require("./generics/deleteNotificationRoutes.js");
const deleteNotificationsRoutes = require("./generics/deleteNotificationsRoutes.js");
const getCustomerIdsRoutes = require("./admins/loanManagement/newLoans/getCustomerIdsRoutes.js");
const setAboutRoutes = require("./admins/configurations/about/setAboutRoutes.js");
const getAboutInfoRoutes = require("./admins/configurations/about/getAboutInfoRoutes.js");
const insertUpdateAdvertRoutes = require("./admins/configurations/adverts/insertUpdateAdvertRoutes.js");
const getAdvertRoutes = require("./admins/configurations/adverts/getAdvertRoutes.js");
const insertBrandImageRoutes = require("./admins/configurations/adverts/insertBrandImageRoutes.js");
const getBrandImagesRoutes = require("./admins/configurations/adverts/getBrandImagesRoutes.js");
const deleteBrandImageRoutes = require("./admins/configurations/adverts/deleteBrandImageRoutes.js");
const resetInterestRatesRoutes = require("./admins/configurations/promotions/resetInterestRatesRoutes.js");
const setDiscountRateRoutes = require("./admins/configurations/promotions/setDiscountRateRoutes.js");
const setSpecialOfferRoutes = require("./admins/configurations/offers/setSpecialOfferRoutes.js");
const getSpecialOffersRoutes = require("./admins/configurations/offers/getSpecialOffersRoutes.js");
const getCustomerSpecialOffersRoutes = require("./admins/configurations/offers/getCustomerSpecialOffersRoutes.js");
const saveFeedbackCategoryRoutes = require("./admins/configurations/feedbacks/saveFeedbackCategoryRoutes.js");
const getFeedbackCategoriesRoutes = require("./admins/configurations/feedbacks/getFeedbackCategoriesRoutes.js");
const saveCustomerFeedbackRoutes = require("./admins/configurations/feedbacks/saveCustomerFeedbackRoutes.js");
const getCustomerFeedbacksRoutes = require("./admins/configurations/feedbacks/getCustomerFeedbacksRoutes.js");
const getInsightsRoutes = require("./admins/dashboard/getInsightsRoutes.js");
const setAgreementRefsRoutes = require("./generics/setAgreementRefsRoutes.js");
const getAgreementRefsRoutes = require("./generics/getAgreementRefsRoutes.js");
const getAgreementInfoRoutes = require("./customers/loans/loanApplications/getAgreementInfoRoutes.js");
const getApplicantAgreementInfoRoutes = require("./admins/loanManagement/loanApplications/getApplicantAgreementInfoRoutes.js");
const getDistrictsRoutes = require("./generics/getDistrictsRoutes.js");
const setResidentialDistrictRoutes = require("./customers/dashboard/setResidentialDistrictRoutes.js");
const getDashboardAnalysisRoutes = require("./admins/dashboard/getDashboardAnalysisRoutes.js");
const setFeedbackReplyRoutes = require("./generics/feedbackReplies/addFeedbackReplyRoutes.js");
const getUserFeedbackRoutes = require("./customers/feedbacks/getUserFeedbackRoutes.js");
const getNumNewFeedbackRepliesRoutes = require("./customers/feedbacks/getNumNewFeedbackRepliesRoutes.js");
const markFeedbackRepliesAsReadRoutes = require("./generics/feedbackReplies/markFeedbackRepliesAsReadRoutes.js");
const getAdminNumNewFeedbackRepliesRoutes = require("./admins/configurations/feedbacks/getAdminNumNewFeedbackRepliesRoutes.js");
const markCustomerFeedbacksAndRepliesAsReadRoutes = require("./admins/configurations/feedbacks/markCustomerFeedbacksAndRepliesAsReadRoutes.js");
const getMonthlyProfitRoutes = require("./admins/dashboard/getMonthlyProfitRoutes.js");

// Savings Application Routes
const saveSavingsApplicationRoutes = require("./customers/savings/setSavingsApplicationRoutes.js");
const getCustomerSavingsApplicationsRoutes = require("./customers/savings/getSavingsApplicationsRoutes.js");
const getSavingsApplicationsRoutes = require("./admins/savings/savings-applications/getSavingsApplicationsRountes.js");
const declineSavingsApplicationRoutes = require("./admins/savings/savings-applications/declineSavingsApplicationRoutes.js");
const approveSavingsApplicationRoutes = require("./admins/savings/savings-records/approveSavingsApplicationROutes.js");
const getSavingsRecordsRoutes = require("./admins/savings/savings-records/getSavingsRecordsRoutes.js");
const withdrawMaturedSavingsROutes = require("./admins/savings/savings-records/withdrawMaturedSavingsROutes.js");
const getSavingsAuditTrailRoutes = require("./admins/savings/audit-trails/getSavingsAutiTrailRoutes.js");
const getSavingsAnalyticsRoutes = require("./admins/savings/analytics/getSavingsAbalyticsRoutes.js");
const fetchConfigRecordRoutes = require("./admins/savings/config/fetchConfigRecordRoutes.js");
const setNewConfigurationsRoutes = require("./admins/savings/config/setNewConfigurationsRoutes.js");
const getNumSavingsApplicationsRoutes = require("./admins/savings/savings-applications/getNumSavingsApplicationsRoutes.js");
const getCustomerApprovedSavingsRoutes = require("./customers/savings/getCustomerApprovedSavingsRoutes.js");
const getCustomerSavingsInsightsRoutes = require("./customers/savings/getCustomerSavingsInsightsRoutes.js");







const registerRoutes = (app) => {

   // Use Routes
   app.use("/api", test);
   
   app.use("/api/auth/login", loginRoutes);
   app.use("/api/auth/updateLoginCredentials", updateLoginCredentialsRoures);
   app.use("/api/auth/logout", logoutRoutes);
   app.use("/api/auth/checkUsername", checkUsername);
   app.use("/api/auth/resetPassword", resetPassword);
   app.use("/api/registerUser", registerUserRoutes);
   app.use("/api/getGenders", getGendersRoutes);
   app.use("/api/updateProfile", updateProfileRoutes);
   app.use("/api/getUsers", getUsersRoutes);
   app.use("/api/toggleAdminRole", toggleAdminRoleRoutes);
   app.use("/api/toggleBlockUser", toggleBlockUserRoutes);
   app.use("/api/savePaymentDetails", savePaymentDetailsRoutes);
   app.use("/api/getPaymentDetails", getPaymentDetailsRoutes);
   app.use("/api/deletePaymentDetails", deletePaymentDetailsRoutes);
   app.use("/api/saveLoanType", saveLoanTypeRoutes);
   app.use("/api/getLoanTypes", getLoanTypesRoutes);
   app.use("/api/deleteLoanType", deleteLoanTypeRoutes);
   app.use("/api/saveInterestRates", saveInterestRatesRoutes);
   app.use("/api/getInterestRates", getInterestRatesRoutes);
   app.use("/api/deleteInterestRates", deleteInterestRatesRoutes);
   app.use("/api/saveTermsAndConditions", saveTermsAndConditionsRoutes);
   app.use("/api/getTermsAndConditions", getTermsAndConditionsRoutes);
   app.use("/api/deleteTermsAndConditions", deleteTermsAndConditionsRoutes);
   app.use("/api/getNumWeeks", getNumWeeksRoutes);
   app.use("/api/saveNewLoan", saveNewLoanRoutes);
   app.use("/api/getUnclearedLoans", getUnclearedLoansRoutes);
   app.use("/api/getOverdueLoans", getOverdueLoansRoutes);
   app.use("/api/deleteLoan", deleteLoanRoutes);
   app.use("/api/loanRepayments", loanRepaymentsRoutes);
   app.use("/api/renewLoan", renewLoanRoutes);
   app.use("/api/getLoanBalance", getLoanBalanceRoutes);
   app.use("/api/getClearedLoans", getClearedLoansRoutes);
   app.use("/api/saveLoanApplication", saveLoanApplicationRoutes);
   app.use("/api/deleteLoanApplication", deleteLoanApplicationRoutes);
   app.use("/api/getLoanApplications", getLoanApplicationsRoutes);
   app.use("/api/getLoanApplicationsAsAdmin", getLoanApplicationsAsAdminRoutes);
   app.use("/api/declineLoanApplication", declineLoanApplicationRoutes);
   app.use("/api/approveLoan", approveLoanRoutes);
   app.use("/api/getCustomerLoans", getCustomerLoansRoutes);
   app.use("/api/getMessages", getMessagesRoutes);
   app.use("/api/updateMessage", updateMessageRoutes);
   app.use("/api/setSystemAttributes", setSystemAttributesRoutes);
   app.use("/api/getSystemAttributes", getSystemAttributesRoutes);
   app.use("/api/getUserDetails", getUserDetailsRoutes);
   app.use("/api/updateDP", updateDPRoutes);
   app.use("/api/sendSMS", sendSMSRoutes);
   app.use("/api/getCustomerLoansStats", getCustomerLoansStatsRoutes);
   app.use("/api/getAdminLoanStats", getAdminLoanStatsRoutes);
   app.use("/api/getUserType", getUserTypeRoutes);
   app.use("/api/getUserNotifications", getUserNotificationsRoutes);
   app.use("/api/markViewedNotifications", markViewedNotificationsRoutes);
   app.use("/api/getNumNewNotifications", getNumNewNotificationsRoutes);
   app.use("/api/deleteNotification", deleteNotificationRoutes);
   app.use("/api/deleteNotifications", deleteNotificationsRoutes);
   app.use("/api/getCustomerIds", getCustomerIdsRoutes);
   app.use("/api/setAbout", setAboutRoutes);
   app.use("/api/getAboutInfo", getAboutInfoRoutes);
   app.use("/api/insertUpdateAdvert", insertUpdateAdvertRoutes);
   app.use("/api/getAdvert", getAdvertRoutes);
   app.use("/api/insertBrandImage", insertBrandImageRoutes);
   app.use("/api/getBrandImagesRoutes", getBrandImagesRoutes);
   app.use("/api/deleteBrandImage", deleteBrandImageRoutes);
   app.use("/api/resetInterestRates", resetInterestRatesRoutes);
   app.use("/api/setDiscountRate", setDiscountRateRoutes);
   app.use("/api/setSpecialOffer", setSpecialOfferRoutes);
   app.use("/api/getSpecialOffers", getSpecialOffersRoutes);
   app.use("/api/getCustomerSpecialOffers", getCustomerSpecialOffersRoutes);
   app.use("/api/saveFeedbackCategory", saveFeedbackCategoryRoutes);
   app.use("/api/getFeedbackCategories", getFeedbackCategoriesRoutes);
   app.use("/api/saveCustomerFeedback", saveCustomerFeedbackRoutes);
   app.use("/api/getCustomerFeedbacks", getCustomerFeedbacksRoutes);
   app.use("/api/getInsights", getInsightsRoutes);
   app.use("/api/setAgreementRefs", setAgreementRefsRoutes);
   app.use("/api/getAgreementRefs", getAgreementRefsRoutes);
   app.use("/api/getAgreementInfo", getAgreementInfoRoutes);
   app.use("/api/getApplicantAgreementInfo", getApplicantAgreementInfoRoutes);
   app.use("/api/getDistricts", getDistrictsRoutes);
   app.use("/api/setResidentialDistrict", setResidentialDistrictRoutes);
   app.use("/api/getDashboardAnalysis", getDashboardAnalysisRoutes);
   
   app.use("/api/setFeedbackReply", setFeedbackReplyRoutes);
   app.use("/api/getUserFeedbacks", getUserFeedbackRoutes);
   app.use("/api/getNumNewFeedbackReplies", getNumNewFeedbackRepliesRoutes);
   app.use("/api/markFeedbackRepliesAsRead", markFeedbackRepliesAsReadRoutes);
   app.use("/api/getAdminNumNewFeedbackReplies", getAdminNumNewFeedbackRepliesRoutes);
   app.use("/api/markCustomerFeedbacksAndRepliesAsRead", markCustomerFeedbacksAndRepliesAsReadRoutes);
   app.use("/api/getMonthlyProfits", getMonthlyProfitRoutes);
   
   // Savings Application Routes
   app.use("/api/saveSavingsApplication", saveSavingsApplicationRoutes);
   app.use("/api/getSavingsApplications", getCustomerSavingsApplicationsRoutes);
   app.use("/api/getSavingsApplicationsForManagement", getSavingsApplicationsRoutes);
   app.use("/api/declineSavingsApplication", declineSavingsApplicationRoutes);
   app.use("/api/approveSavingsApplication", approveSavingsApplicationRoutes);
   app.use("/api/getSavingsRecords", getSavingsRecordsRoutes);
   app.use("/api/withdrawMaturedSavings", withdrawMaturedSavingsROutes);
   app.use("/api/getSavingsAuditTrail", getSavingsAuditTrailRoutes);
   app.use("/api/getSavingsAnalytics", getSavingsAnalyticsRoutes);
   app.use("/api/fetchSavingsConfig", fetchConfigRecordRoutes);
   app.use("/api/setSavingsConfigurations", setNewConfigurationsRoutes);
   app.use("/api/getNumSavingsApplications", getNumSavingsApplicationsRoutes);
   app.use("/api/getCustomerApprovedSavings", getCustomerApprovedSavingsRoutes);
   app.use("/api/getCustomerSavingsInsights", getCustomerSavingsInsightsRoutes);
}

module.exports = registerRoutes;